### ISSUE TITLE
[Feature] indication of draft status

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#10]
As a user I want to know that a new PR in my inbox is a "draft" 
so that I can quickly determine that i don't need to read any details right now,
because the developer isn't done working on it.

**Comment by dacharyc** [comment]
I'm undecided about whether to support this behavior. I hadn't intended the inbox to be a long-term store for PRs - I had envisioned folks to go through the inbox when they have time, decide whether to watch or ignore the PR, and clear the inbox. I don't want the cognitive load of seeing a draft PR in an inbox long-term and having to decide every time I see it whether to ignore or watch it.

As an alternative, how would you feel about a setting that you can toggle for whether or not to show draft PRs in your inbox? I could provide a setting like Show Drafts, and when Show Drafts is not selected, simply not create the PR until it is no longer in draft.

Your use case is the opposite of mine - I _want_ to see draft PRs and decide whether I will need to do some action based on them, so I would watch or ignore them right away. With this in mind, a setting seems like it might make more sense. What are your thoughts?

**Comment by dacharyc** [comment]
After living with PR Focus for several months, I agree this is a good improvement. I added the feature in [v0.3](https://github.com/dacharyc/prfocus-website/blob/main/CHANGELOG.md#new-features). The PR summary for a PR now has a "Draft" status icon, which you can see in [the Status docs](https://prfocus.app/docs/repositories/view-repository/#status).

I'm capturing the idea of a setting for show or hide drafts as a possible future improvement, but I'm going to go ahead and close this feature request since I've now implemented the requested feature.

Thanks for the suggestion!
