### ISSUE TITLE
[Feature] App: Filter and/or Sort PRs by attribute

### ISSUE THREAD

**Issue by ccho-mongodb** [dacharyc/prfocus-website#11]
**Is your feature request related to a problem? Please describe.**
What problem would this feature solve? Ex. I'm always frustrated when [...]
At a glance, I would like to see which PRs are at risk of taking an extended time to close. I might try to locate this by locating ones that have many reviews or many comments.

**Describe the solution you'd like**
Filter and/or sort PRs by a specific attribute in a table view. 

**Describe alternatives you've considered**
Is there something else that might make sense, instead?
Perhaps a filter menu, similar to what you mind find on e-commerce sites. E.g. search for in-stock long sleeve shirts that are in size "M".

**Additional context**
Is this related to a specific workflow that your organization or repository uses? If so, please tell me more about your workflow to help me understand your request.
As a staff writer, I attempt to make sure that my team addresses stale PRs and finds the best path forward for contentious PRs. Without PR Focus, it requires searching all the repos on the web which takes time. I think that having a full view across repos is beneficial, but would also like to make use of the meta information to expedite the search.

**Labels**
Let me know whether your feature is related to the PR Focus app or website. I've pre-selected the app for your convenience, but please remove the app label and change it to website, instead, if your suggestion is for the website.

**Comment by dacharyc** [comment]
Thank you for suggesting this feature! I do have a backlog item for myself to add sorting and possibly filtering, but was thinking more of date of activity, merge conflict status, or failing checks. I hadn't considered the number of reviews or comments to be particularly useful metadata as a sort metric.

I'm still thinking through UX and design considerations for filtering, but I should be able to add sorting in a relatively short timeframe. I'll allocate this feature to next week's build and will update here if I need to change it to a different milestone.

**Comment by dacharyc** [comment]
I've added sorting to the upcoming build that I intend to release for Monday! Based on your request here, I've added the ability to sort each column in a dashboard by:

- Review count
- Comment count
- Commit count
- State (Open/Closed/Merged)
- "Broken" (has merge conflicts or failing status checks)
- Updated date
- Closed date
- Merged date

Sort defaults to updated date, which is the current behavior.

My opinionated design for PR Focus means I want to never have an important pull request "disappear." So I've chosen to implement these as sort options instead of filtering, so PRs don't disappear - you can just bring the most important ones to the top of the list based on whatever metric you choose. Sort selections do not persist if you go into a different view and then return to the dashboard, because showing the PRs in order of most recently updated is most consistent with the design driving PR Focus.
