### ISSUE TITLE
[Feature] App - dark mode related UI changes

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#17]
as a user I want to be able to have clear visual distinctions between PRs with new information and PRs with old, even when my computer is in dark mode.

The visual differences in the current darkmode aren't significant enough for me. 

<img width="502" alt="CleanShot 2023-09-14 at 07 40 00@2x" src="https://github.com/dacharyc/prfocus-website/assets/2829/069a1774-9f06-456e-a976-90ad9325993d">

I'm thinking i would like one or both of the following. Both would be best:
- more distinct visual differences in dark mode
- the ability to toggle off dark mode even when my computer is in dark mode

**Comment by dacharyc** [comment]
Thanks for the enhancement request! I can understand the perspective that there's not enough visual distinction between the PR row colors in dark mode. I've made the lighter version significantly brighter in the upcoming build, which I plan to release Monday.

Per an offline discussion, I've also swapped the meaning of the two colors. The "brighter" row color now indicates when a PR has updates, versus the "darker" row color indicating the PR updates have been viewed. I'm considering this a "breaking" change because it reverses the meaning of the colors - it's not just a change to the brightness of one of the colors. Because this is a breaking change, I'll consider feedback from all of my testers and may revert the color swap based on feedback.

Regarding the ability to toggle off dark mode even when the computer is in dark mode, that's not a change I'm interested in making at this time. The development changes required to support this functionality are substantial, and it's not something I intend to target for v1. If you would still like to see the ability to toggle PR Focus into light/dark mode independent of the system color, please make a separate feature request. I would consider prioritizing such a feature request for a much later future version based on how many people were interested in similar functionality.

**Comment by dacharyc** [comment]
After using this with the swapped colors for several months, I haven't been able to adjust to the color change. I still have cognitive confusion about the grey vs. black as which one is "brighter." I'm reverting these color changes in v0.3 Build 1. If you have additional feedback about this after the change, please do post here. I'll keep an eye on this issue to see if other people have thoughts on what the appropriate color scheme should be.
