### ISSUE TITLE
[Bug] App - errors if API token has no expiration date

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#24]
**Describe the bug**
Can't add repos with non-expiring token

see logs in screenshot

**To Reproduce**
make a classic token with no expiration and try to use it.

**Expected behavior**
it should work.

**Actual Behavior**
it doesn't work because of an error validating the expiration date.

**Screenshots**
![CleanShot 2024-03-17 at 17 09 19@2x](https://github.com/dacharyc/prfocus-website/assets/2829/349b40b6-e231-40bc-9613-60bb815b781c)

**Comment by dacharyc** [comment]
Thanks for reporting this! I added a lot of additional validation around API key expiry and totally missed handling the case where people create a token with no expiration date. 

I'm trying to decide if this is something I want to support. I don't want PR Focus to become a security risk because people are using it with tokens that never expire. I could definitely surface a more meaningful error message, though. I'll have a think about the best way to handle this.

In the meantime, please create a token with an expiration date and that should resolve this issue.

Sorry for the inconvenience!

**Comment by dacharyc** [comment]
I've decided to disallow API access tokens with no expiration date. I've added better error handling around this, so you can now no longer provide an API access token with no expiration date.

Thanks for bringing this to my attention!

**Comment by masukomi** [comment]
Woot!
