### ISSUE TITLE
[FEATURE] app wider sidebar for easier viewing of repo names

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#44]
as a user wanting to find a specific repo in the list
i wish to be able to see more of the name of the repo
so that i can more easily distinguish between ones with the same prefix and not have to deal with the extra mental thinking that comes from encountering an elipsis & needing to figure out the missing info.

looking at the following screenshot it seems like exceeding the available width is not an uncommon thing. I recognize that i can rename the repos but then i have to memorize some translation between short name here & the name i deal with everywhere else. 

![CleanShot 2024-07-26 at 10 52 10@2x](https://github.com/user-attachments/assets/fd49b641-3043-4cc4-86d9-15c01b83351e)

![CleanShot 2024-07-26 at 10 35 25@2x](https://github.com/user-attachments/assets/211d01f6-2fde-47f3-8d01-6aab9cb00319)

**Comment by dacharyc** [comment]
Hey there - the window and sidebar are resizable, so you should be able to make it as wide as you need to in order to accommodate the names. I have set a minimum width and minimum height for the app windows to try to make sure everything displays properly, but there's nothing to prevent you from making it bigger in either direction.

I was just testing and it seems that sizing is - somewhat? preserved between launches. So if you make the window and the sidebar larger, it seems to retain at least some of that, but it wasn't consistent for me between launches.

I can dig more into this behavior. In the meantime, it should be _possible_ for me to provide settings to allow you to specify your own minimum width and height if you want to make the app always launch bigger. Is that something you'd be interested in using, or is it enough to know you can resize the sidebar however you like?

**Comment by dacharyc** [comment]
Having done a little more testing and spoken with you offline about this, it seems the ability to resize it yourself is enough for your use case. I'd prefer to avoid adding more settings to muck with if people don't really need them. So I'm going to go ahead and close this request. Feel free to re-open in the future if you change your mind about manually specifying a minimum width!
